spring:
  profiles:
    active: dev

  #文件上传大小配置 单个文件大小 总的文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

      #日志
#logging:
#  config: classpath:logback-spring.xml
#  level:
#  com.m.dbaccess.mapper: debug

#开启swagger注解
swagger:
  enabled: true
